/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator */

#ifndef _Included_Calculator
#define _Included_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    rest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_rest
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_divide
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
